import { db } from '@/lib/db';
import { NextRequest } from 'next/server';
import { emailService } from '@/lib/notifications/email.service';

export interface AuditEventInput {
  adminId: string;
  adminEmail: string;
  action: string;
  resource: string;
  resourceId?: string;
  details?: Record<string, any>;
  request?: NextRequest;
}

/**
 * Log an admin action to the persistent audit log.
 * Fire-and-forget — errors are caught and logged, never thrown.
 * Also checks for suspicious patterns after logging.
 */
export async function logAuditEvent(input: AuditEventInput): Promise<void> {
  try {
    const ipAddress = input.request?.headers.get('x-forwarded-for')
      ?? input.request?.headers.get('x-real-ip')
      ?? undefined;
    const userAgent = input.request?.headers.get('user-agent') ?? undefined;

    await db.auditLog.create({
      data: {
        adminId: input.adminId,
        adminEmail: input.adminEmail,
        action: input.action,
        resource: input.resource,
        resourceId: input.resourceId,
        details: input.details ?? undefined,
        ipAddress: ipAddress ?? null,
        userAgent: userAgent ? userAgent.substring(0, 500) : null,
      },
    });

    // Check for suspicious patterns (non-blocking)
    checkSuspiciousPatterns(input.adminId, input.action, ipAddress ?? null).catch(() => {});
  } catch (error) {
    // Never let audit logging break the main request
    console.error('Failed to write audit log:', error);
  }
}

// ==================== SUSPICIOUS PATTERN DETECTION ====================

const ALERT_THRESHOLDS = {
  FAILED_LOGINS_WINDOW_MS: 15 * 60 * 1000,   // 15 minutes
  FAILED_LOGINS_MAX: 5,                        // 5 failed logins
  SENSITIVE_ACTIONS_WINDOW_MS: 10 * 60 * 1000, // 10 minutes
  SENSITIVE_ACTIONS_MAX: 10,                    // 10 sensitive actions in window
  NEW_IP_CHECK: true,                          // Alert on new IP for admin
};

const SENSITIVE_ACTIONS = [
  'USER_PASSWORD_RESET',
  'USER_SUSPENDED',
  'SETTINGS_UPDATED',
  'EXTENSION_REFUNDED',
  'SESSION_INVALIDATED',
];

// ---- Real-time email alert for suspicious activity ----

const ALERT_RECIPIENTS = (process.env.SECURITY_ALERT_EMAIL || process.env.ADMIN_EMAIL || '').split(',').filter(Boolean);

// Simple in-memory cooldown to prevent alert floods (1 alert per pattern per 15 min)
const alertCooldowns = new Map<string, number>();
const ALERT_COOLDOWN_MS = 15 * 60 * 1000;

async function sendSecurityAlert(
  alertType: string,
  reason: string,
  details: Record<string, any>
): Promise<void> {
  if (ALERT_RECIPIENTS.length === 0) return;

  const cooldownKey = `${alertType}:${details.adminId || 'unknown'}`;
  const lastSent = alertCooldowns.get(cooldownKey) || 0;
  if (Date.now() - lastSent < ALERT_COOLDOWN_MS) return;
  alertCooldowns.set(cooldownKey, Date.now());

  const timestamp = new Date().toISOString();
  const detailRows = Object.entries(details)
    .map(([k, v]) => `<tr><td style="padding:6px 12px;font-weight:600;color:#6b7280;border-bottom:1px solid #f3f4f6">${k}</td><td style="padding:6px 12px;border-bottom:1px solid #f3f4f6">${typeof v === 'object' ? JSON.stringify(v) : v}</td></tr>`)
    .join('');

  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#dc2626;color:white;padding:20px 24px;border-radius:12px 12px 0 0">
        <h2 style="margin:0;font-size:18px">Security Alert: ${alertType}</h2>
        <p style="margin:4px 0 0;opacity:0.9;font-size:13px">${timestamp}</p>
      </div>
      <div style="border:1px solid #e5e7eb;border-top:none;padding:24px;border-radius:0 0 12px 12px">
        <p style="margin:0 0 16px;color:#111827;font-size:15px"><strong>${reason}</strong></p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;color:#374151">${detailRows}</table>
        <p style="margin:20px 0 0;font-size:12px;color:#9ca3af">This alert was generated by InstaCares security monitoring. Review in the <a href="https://instacares.net/admin" style="color:#2563eb">Admin Dashboard &rarr; Audit Log</a>.</p>
      </div>
    </div>`;

  try {
    await emailService.send({
      to: ALERT_RECIPIENTS,
      subject: `[InstaCares Security] ${alertType}: ${reason.substring(0, 80)}`,
      html,
    });
  } catch (err) {
    console.error('Failed to send security alert email:', err);
  }
}

// ---- Pattern detection ----

async function checkSuspiciousPatterns(
  adminId: string,
  action: string,
  ip: string | null
): Promise<void> {
  try {
    const now = new Date();

    // Pattern 1: Too many failed logins from same email
    if (action === 'LOGIN_FAILED') {
      const windowStart = new Date(now.getTime() - ALERT_THRESHOLDS.FAILED_LOGINS_WINDOW_MS);
      const recentFailures = await db.auditLog.count({
        where: {
          adminId,
          action: 'LOGIN_FAILED',
          createdAt: { gte: windowStart },
        },
      });

      if (recentFailures >= ALERT_THRESHOLDS.FAILED_LOGINS_MAX) {
        const reason = `${recentFailures} failed logins in ${ALERT_THRESHOLDS.FAILED_LOGINS_WINDOW_MS / 60000} minutes`;
        await logAuditEvent({
          adminId,
          adminEmail: adminId,
          action: AuditActions.SUSPICIOUS_ACTIVITY,
          resource: 'auth',
          details: { reason, triggerAction: 'LOGIN_FAILED', ip },
        });
        sendSecurityAlert('Brute Force Attempt', reason, { adminId, ip: ip || 'unknown', failedCount: recentFailures }).catch(() => {});
      }
    }

    // Pattern 2: Burst of sensitive actions
    if (SENSITIVE_ACTIONS.includes(action)) {
      const windowStart = new Date(now.getTime() - ALERT_THRESHOLDS.SENSITIVE_ACTIONS_WINDOW_MS);
      const recentSensitive = await db.auditLog.count({
        where: {
          adminId,
          action: { in: SENSITIVE_ACTIONS },
          createdAt: { gte: windowStart },
        },
      });

      if (recentSensitive >= ALERT_THRESHOLDS.SENSITIVE_ACTIONS_MAX) {
        const reason = `${recentSensitive} sensitive actions in ${ALERT_THRESHOLDS.SENSITIVE_ACTIONS_WINDOW_MS / 60000} minutes`;
        await db.auditLog.create({
          data: {
            adminId,
            adminEmail: adminId,
            action: AuditActions.SUSPICIOUS_ACTIVITY,
            resource: 'auth',
            details: { reason, recentActions: SENSITIVE_ACTIONS, ip },
          },
        });
        sendSecurityAlert('Sensitive Action Burst', reason, { adminId, ip: ip || 'unknown', actionCount: recentSensitive, actions: SENSITIVE_ACTIONS.join(', ') }).catch(() => {});
      }
    }

    // Pattern 3: Admin logging in from new IP
    if (action === 'LOGIN_SUCCESS' && ip) {
      const knownIPs = await db.auditLog.findMany({
        where: {
          adminId,
          action: 'LOGIN_SUCCESS',
          ipAddress: { not: null },
          createdAt: { gte: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000) },
        },
        select: { ipAddress: true },
        distinct: ['ipAddress'],
      });

      const knownIPSet = new Set(knownIPs.map(l => l.ipAddress));
      if (knownIPSet.size > 0 && !knownIPSet.has(ip)) {
        await db.auditLog.create({
          data: {
            adminId,
            adminEmail: adminId,
            action: AuditActions.SUSPICIOUS_ACTIVITY,
            resource: 'auth',
            details: { reason: 'Login from previously unseen IP address', newIP: ip, knownIPs: Array.from(knownIPSet) },
          },
        });
        sendSecurityAlert('New IP Login', 'Login from previously unseen IP address', { adminId, newIP: ip, knownIPs: Array.from(knownIPSet).join(', ') }).catch(() => {});
      }
    }
  } catch (error) {
    console.error('Suspicious pattern check error:', error);
  }
}

// ==================== LOG RETENTION POLICY ====================

const DEFAULT_RETENTION_DAYS = 365; // 1 year

/**
 * Purge audit logs older than the retention period.
 * Call this from a cron job or admin endpoint.
 */
export async function purgeOldAuditLogs(retentionDays: number = DEFAULT_RETENTION_DAYS): Promise<number> {
  const cutoff = new Date(Date.now() - retentionDays * 24 * 60 * 60 * 1000);
  const result = await db.auditLog.deleteMany({
    where: { createdAt: { lt: cutoff } },
  });
  return result.count;
}

// ==================== SESSION INVALIDATION ====================

/**
 * Invalidate a user's session by deactivating their account.
 * With JWT strategy, the session callback refreshes isActive from DB
 * on every request, so the user will be blocked on next API call.
 * They must re-login (which will also fail since isActive=false).
 */
export async function invalidateUserSessions(
  userId: string,
  reason: string,
  triggeredBy: string
): Promise<void> {
  // Deactivate the user — JWT callback checks isActive on every request
  await db.user.update({
    where: { id: userId },
    data: { isActive: false },
  });

  // Log the invalidation
  await logAuditEvent({
    adminId: triggeredBy,
    adminEmail: triggeredBy,
    action: AuditActions.SESSION_INVALIDATED,
    resource: 'auth',
    resourceId: userId,
    details: { reason },
  });
}

// Common action constants
export const AuditActions = {
  USER_APPROVED: 'USER_APPROVED',
  USER_REJECTED: 'USER_REJECTED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  CHAT_FLAGGED: 'CHAT_FLAGGED',
  CHAT_NOTICE_SENT: 'CHAT_NOTICE_SENT',
  CHAT_BULK_ACTION: 'CHAT_BULK_ACTION',
  CAREGIVER_WARNING_ISSUED: 'CAREGIVER_WARNING_ISSUED',
  CAREGIVER_DETAILED_APPROVAL: 'CAREGIVER_DETAILED_APPROVAL',
  PAYOUT_PROCESSED: 'PAYOUT_PROCESSED',
  EXTENSION_APPROVED: 'EXTENSION_APPROVED',
  EXTENSION_REFUNDED: 'EXTENSION_REFUNDED',
  BABYSITTER_STATUS_CHANGED: 'BABYSITTER_STATUS_CHANGED',
  VERIFICATION_UPDATED: 'VERIFICATION_UPDATED',
  REVIEW_MODERATED: 'REVIEW_MODERATED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_RATE_LIMITED: 'LOGIN_RATE_LIMITED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  SESSION_INVALIDATED: 'SESSION_INVALIDATED',
} as const;
