module.exports = {
  apps: [
    {
      name: 'instacares-staging',
      script: 'node_modules/.bin/next',
      args: 'start -p 3007',
      cwd: '/var/www/instacares-staging',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '400M',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
        NEXTAUTH_URL: 'https://staging.instacares.net',
        NEXT_PUBLIC_BASE_URL: 'https://staging.instacares.net',
        NEXT_PUBLIC_SOCKET_URL: 'https://staging.instacares.net',
        PAYMENT_MODE: 'test',
      },
      kill_timeout: 5000,
      listen_timeout: 10000,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      error_file: '/var/www/instacares-staging/logs/pm2-error.log',
      out_file: '/var/www/instacares-staging/logs/pm2-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'socket-server-staging',
      script: 'socket-server.js',
      cwd: '/var/www/instacares-staging',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        PORT: 3008,
      },
      kill_timeout: 5000,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      error_file: '/var/www/instacares-staging/logs/socket-error.log',
      out_file: '/var/www/instacares-staging/logs/socket-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
