name: Deploy InstaCares

on:
  push:
    branches:
      - main        # Deploy to production from main branch
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          touch .env.local
          echo "DATABASE_URL=file:./dev.db" >> .env.local
          echo "JWT_SECRET=test-secret-key" >> .env.local
          echo "NEXT_PUBLIC_BASE_URL=http://localhost:3005" >> .env.local

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build application
        run: |
          export SKIP_ENV_VALIDATION=true
          npm run build
        env:
          SKIP_ENV_VALIDATION: true

      - name: Success message
        run: echo "✅ Build completed successfully!"

  deploy-production:
    name: Deploy to Production
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deployment placeholder
        run: |
          echo "🚀 Ready for deployment to Hostinger"
          echo "Deploy manually via Hostinger control panel or SSH"
          echo "✅ Workflow completed successfully!"